use drinknow;

CREATE TABLE users(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(180) NOT NULL,
birthdate DATE NOT NULL,
document BIGINT NOT NULL UNIQUE,
email VARCHAR(180) NOT NULL UNIQUE,
password VARCHAR(90) NOT NULL,
created_at TIMESTAMP(0) NOT NULL,
updated_at TIMESTAMP(0) NOT NULL
);

